// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8HuOiN93kZjl10qkQlaBay2YAtxYazU',
    appId: '1:875217628431:web:495efacbbe7ae9f163e27a',
    messagingSenderId: '875217628431',
    projectId: 'pets-ef1b0',
    authDomain: 'pets-ef1b0.firebaseapp.com',
    storageBucket: 'pets-ef1b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZb9cHwoxjWr8ZGs9JXWKRLV3umyB-tMs',
    appId: '1:875217628431:android:c5b0e4d165b87ef263e27a',
    messagingSenderId: '875217628431',
    projectId: 'pets-ef1b0',
    storageBucket: 'pets-ef1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUdOkpi91F6wD4_UQQOirMJmXSFHfuV8',
    appId: '1:875217628431:ios:e099cb99505ac20963e27a',
    messagingSenderId: '875217628431',
    projectId: 'pets-ef1b0',
    storageBucket: 'pets-ef1b0.appspot.com',
    iosBundleId: 'com.example.pets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUdOkpi91F6wD4_UQQOirMJmXSFHfuV8',
    appId: '1:875217628431:ios:e099cb99505ac20963e27a',
    messagingSenderId: '875217628431',
    projectId: 'pets-ef1b0',
    storageBucket: 'pets-ef1b0.appspot.com',
    iosBundleId: 'com.example.pets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW8HuOiN93kZjl10qkQlaBay2YAtxYazU',
    appId: '1:875217628431:web:62f73fa928811de563e27a',
    messagingSenderId: '875217628431',
    projectId: 'pets-ef1b0',
    authDomain: 'pets-ef1b0.firebaseapp.com',
    storageBucket: 'pets-ef1b0.appspot.com',
  );

}